# Generated by Django 3.0.3 on 2020-03-26 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField(blank=True)),
                ('slogan', models.CharField(max_length=50)),
                ('group', models.CharField(max_length=50)),
                ('tag', models.CharField(choices=[('As', 'Astronauts'), ('Bo', 'Books'), ('Bu', 'Business'), ('Cr', 'Crime'), ('Dr', 'Drugs'), ('Ed', 'Education'), ('En', 'Entertainment'), ('Fi', 'Finance'), ('Fo', 'Food & Drink'), ('He', 'Health & Fitness'), ('Je', 'Jesus'), ('Ki', 'Kids'), ('Li', 'Lifestyle'), ('Ma', 'Magazines & Newspapers'), ('Me', 'Medical'), ('Mu', 'Music'), ('Na', 'Navigation'), ('Ne', 'News'), ('Ns', 'NSFW'), ('Ph', 'Photo & Video'), ('Pr', 'Productivity'), ('Re', 'Reference'), ('Sh', 'Shopping'), ('So', 'Social Networking'), ('Sp', 'Sports'), ('Tr', 'Travel'), ('Ut', 'Utilities'), ('We', 'Weather'), ('Ot', 'Other')], default='Ot', max_length=2)),
                ('net_votes', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(-1, 'BAD'), (1, 'GOOD')])),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.App')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.App')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.TextField(blank=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.App')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
