# Generated by Django 3.0.2 on 2020-03-26 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200326_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='group',
            new_name='developer',
        ),
    ]
