# Generated by Django 3.0.3 on 2020-03-23 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_comment_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='app',
        ),
    ]
