# Generated by Django 3.0.2 on 2020-03-27 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200327_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='words',
            field=models.TextField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.IntegerField(choices=[(1, 'GOOD'), (-1, 'BAD')]),
        ),
    ]
