# Generated by Django 3.0.3 on 2020-03-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_comment_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='slogan',
            field=models.TextField(blank=True),
        ),
    ]
