# Generated by Django 3.0.2 on 2020-03-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20200327_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.IntegerField(choices=[(-1, 'BAD'), (1, 'GOOD')]),
        ),
    ]
