# Generated by Django 3.0.2 on 2020-03-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20200323_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='net_votes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='value',
            field=models.IntegerField(choices=[(1, 'GOOD'), (-1, 'BAD')], default=1),
            preserve_default=False,
        ),
    ]
