# Generated by Django 3.0.2 on 2020-03-24 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20200324_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='tag',
            field=models.CharField(choices=[('As', 'Astronauts'), ('Bo', 'Books'), ('Bu', 'Business'), ('Cr', 'Crime'), ('Dr', 'Drugs'), ('Ed', 'Education'), ('En', 'Entertainment'), ('Fi', 'Finance'), ('Fo', 'Food & Drink'), ('He', 'Health & Fitness'), ('Je', 'Jesus'), ('Ki', 'Kids'), ('Li', 'Lifestyle'), ('Ma', 'Magazines & Newspapers'), ('Me', 'Medical'), ('Mu', 'Music'), ('Na', 'Navigation'), ('Ne', 'News'), ('Ns', 'NSFW'), ('Ph', 'Photo & Video'), ('Pr', 'Productivity'), ('Re', 'Reference'), ('Sh', 'Shopping'), ('So', 'Social Networking'), ('Sp', 'Sports'), ('Tr', 'Travel'), ('Ut', 'Utilities'), ('We', 'Weather'), ('Ot', 'Other')], default='Ot', max_length=2),
        ),
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.IntegerField(choices=[(-1, 'BAD'), (1, 'GOOD')]),
        ),
    ]
