# Generated by Django 3.0.3 on 2020-03-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20200324_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.IntegerField(choices=[(1, 'GOOD'), (-1, 'BAD')]),
        ),
    ]
