# Generated by Django 3.0.2 on 2020-03-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20200325_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.IntegerField(choices=[(-1, 'BAD'), (1, 'GOOD')]),
        ),
    ]
