# Generated by Django 3.0.2 on 2020-03-25 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20200325_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='value',
        ),
    ]
