# Generated by Django 3.0.2 on 2020-03-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_remove_vote_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='value',
            field=models.IntegerField(choices=[(1, 'GOOD'), (-1, 'BAD')], default=1),
            preserve_default=False,
        ),
    ]
